name: SCUS_942.36
sha1: 81cbc79f0230aeb4252e058039f47ac95a777f5a
options:
  basename: scus_942.36
  target_path: ./iso/us/SCUS_942.36
  elf_path: ./build/scus_942.36/scus_942.36.elf
  base_path: ../../
  platform: psx
  compiler: PSYQ

  asm_path: ./asm/scus_942.36
  src_path: ./src/scus_942.36
  build_path: ./build
  asset_path: ./assets/scus_942.36
  # create_asm_dependencies: True
  generate_asm_macros_files : False

  ld_script_path: ./linker/scus_942.36/scus_942.36.ld
  ld_dependencies: True

  find_file_boundaries: False
  gp_value: 0x80097FA8
  global_vram_start: 0x80010000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  disassemble_all: true

  section_order: [".rodata", ".text", ".data", ".sdata", ".bss", ".sbss"]
  #auto_link_sections: [".data", ".rodata", ".bss"]
  #migrate_rodata_to_functions: true

  symbol_addrs_path:
    - ./symbols/scus_942.36/symbol_addrs.txt
  reloc_addrs_path:
    - ./symbols/scus_942.36/reloc_addrs.txt

  undefined_funcs_auto_path: ./linker/scus_942.36/undefined_funcs_auto.scus_942.36.txt
  undefined_syms_auto_path: ./linker/scus_942.36/undefined_syms_auto.scus_942.36.txt

  extensions_path: ./tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: True
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x0800
    vram: 0x80010000
    # bss_size: 0x2116f
    align: 4
    subsegments:
      - [0x800, rodata]
      - [0x62D8, .rodata, psyq/libgpu/prim]
      - [0x63A8, .rodata, psyq/libgpu/sys]
      - [0x65DC, .rodata, psyq/libgpu/tmd]
      - [0x6714, rodata]
      - [0x6BB0, c, main/main]
      - [0x6CFC, c, main/main_loop]
      - [0x4BB8C, hasm, psyq/libapi/c68]
      - [0x4BB9C, hasm, psyq/libapi/c112]
      - [0x4BBAC, hasm, psyq/libapi/a08]
      - [0x4BBBC, hasm, psyq/libapi/a09]
      - [0x4BBCC, hasm, psyq/libapi/a11]
      - [0x4BBDC, hasm, psyq/libapi/a12]
      - [0x4BBEC, hasm, psyq/libapi/a14]
      - [0x4BBFC, hasm, psyq/libapi/a15]
      - [0x4BC0C, hasm, psyq/libapi/a16]
      - [0x4BC1C, hasm, psyq/libapi/a36]
      - [0x4BC2C, hasm, psyq/libapi/a37]
      - [0x4BC3C, hasm, psyq/libapi/a50]
      - [0x4BC4C, hasm, psyq/libapi/a51]
      - [0x4BC5C, hasm, psyq/libapi/a52]
      - [0x4BC6C, hasm, psyq/libapi/a53]
      - [0x4BC7C, hasm, psyq/libapi/a54]
      - [0x4BC8C, hasm, psyq/libapi/a65]
      - [0x4BC9C, hasm, psyq/libapi/a67]
      - [0x4BCAC, hasm, psyq/libapi/a69]
      - [0x4BCBC, c, psyq/libapi/a94]
      - [0x4BCCC, c, psyq/libapi/func_8005B4CC]
      - [0x4BE68, c, psyq/libapi/func_8005B668]
      - [0x4BF6C, hasm, psyq/libapi/a66]
      - [0x4BF7C, c, psyq/libc2/bcopy]
      - [0x4BFB0, c, psyq/libc2/bzero]
      - [0x4BFE0, c, psyq/libc2/memcpy]
      - [0x4C014, c, psyq/libc2/memset]
      - [0x4C044, c, psyq/libc2/rand]
      - [0x4C084, c, psyq/libc2/strcat]
      - [0x4C12C, c, psyq/libc2/strcmp]
      - [0x4C190, c, psyq/libc2/strcpy]
      - [0x4C1D4, c, psyq/libc2/strlen]
      - [0x4C204, c, psyq/libc2/strncat]
      - [0x4C278, c, psyq/libc2/strncpy]
      - [0x4C2F0, c, psyq/libc2/strstr]
      - [0x4C364, c, psyq/libc2/printf]
      - [0x4C3A0, c, psyq/libc2/prnt]
      - [0x4CA28, c, psyq/libc2/ctype]
      - [0x4CA88, c, psyq/libc2/memchr]
      - [0x4CAD8, c, psyq/libc2/putchar]
      - [0x4CB8C, c, psyq/libc2/sprintf]
      - [0x4D3E8, c, psyq/libc2/memmove]
      #- [0x4BFE0, c, psyq/libc]
      - [0x4D454, c, psyq/libcard]
      - [0x4D7E8, c, psyq/libpress]
      - [0x4E2E0, c, psyq/libgpu/ext]
      - [0x4E5A8, c, psyq/libgpu/prim]
      - [0x4EE94, c, psyq/libgpu/sys]
      - [0x51F28, hasm, psyq/libapi/c73]
      - [0x51F38, c, psyq/libgpu/tmd]
      - [0x536D4, c, psyq/libgte]
      - [0x54E34, c, psyq/libcd]
      - [0x58614, c, psyq/libetc]
      - [0x5BF1C, c, psyq/libsnd]
      - [0x648D4, c, psyq/libspu]
      - [0x67638, data]
      - [0x887A8, sdata]
  - [0x88800]
