name: SCUS_942.36
sha1: 81cbc79f0230aeb4252e058039f47ac95a777f5a
options:
  basename: scus_942.36
  target_path: ./iso/us/SCUS_942.36
  elf_path: ./build/scus_942.36/scus_942.36.elf
  base_path: ../../
  platform: psx
  compiler: PSYQ

  asm_path: ./asm/scus_942.36
  src_path: ./src/scus_942.36
  build_path: ./build
  asset_path: ./assets/scus_942.36
  # create_asm_dependencies: True
  generate_asm_macros_files : False

  ld_script_path: ./linker/scus_942.36/scus_942.36.ld
  ld_dependencies: True

  find_file_boundaries: False
  gp_value: 0x80097FA8
  global_vram_start: 0x80010000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  disassemble_all: true

  section_order: [".rodata", ".text", ".data", ".sdata", ".bss", ".sbss"]
  #auto_link_sections: [".data", ".rodata", ".bss"]
  #migrate_rodata_to_functions: true

  symbol_addrs_path:
    - ./symbols/scus_942.36/symbol_addrs.txt
  reloc_addrs_path:
    - ./symbols/scus_942.36/reloc_addrs.txt

  undefined_funcs_auto_path: ./linker/scus_942.36/undefined_funcs_auto.scus_942.36.txt
  undefined_syms_auto_path: ./linker/scus_942.36/undefined_syms_auto.scus_942.36.txt

  extensions_path: ./tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: True
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x0800
    vram: 0x80010000
    # bss_size: 0x2116f
    align: 4
    subalign: 4
    subsegments:
      - [0x800,  rodata]
      - [0x42A0, .rodata, main/events]
      - [0x4304, rodata]
      - [0x5F3C, .rodata, psyq/libc2/prnt]
      - [0x6150, .rodata, psyq/libc2/sprintf]
      - [0x622C, rodata]
      - [0x62D8, .rodata, psyq/libgpu/prim]
      - [0x63A8, .rodata, psyq/libgpu/sys]
      - [0x65DC, .rodata, psyq/libgpu/tmd]
      - [0x6714, .rodata, psyq/libcd/event]
      - [0x672C, .rodata, psyq/libcd/sys]
      - [0x6734, .rodata, psyq/libcd/bios]
      - [0x6984, rodata]
      - [0x6BB0, c, main/main]
      - [0x2FA68, c, main/events]
      - [0x3197c, c, main/temp]
      - [0x4BB8C, hasm, psyq/libapi/c68]
      - [0x4BB9C, hasm, psyq/libapi/c112]
      - [0x4BBAC, hasm, psyq/libapi/a08]
      - [0x4BBBC, hasm, psyq/libapi/a09]
      - [0x4BBCC, hasm, psyq/libapi/a11]
      - [0x4BBDC, hasm, psyq/libapi/a12]
      - [0x4BBEC, hasm, psyq/libapi/a14]
      - [0x4BBFC, hasm, psyq/libapi/a15]
      - [0x4BC0C, hasm, psyq/libapi/a16]
      - [0x4BC1C, hasm, psyq/libapi/a36]
      - [0x4BC2C, hasm, psyq/libapi/a37]
      - [0x4BC3C, hasm, psyq/libapi/a50]
      - [0x4BC4C, hasm, psyq/libapi/a51]
      - [0x4BC5C, hasm, psyq/libapi/a52]
      - [0x4BC6C, hasm, psyq/libapi/a53]
      - [0x4BC7C, hasm, psyq/libapi/a54]
      - [0x4BC8C, hasm, psyq/libapi/a65]
      - [0x4BC9C, hasm, psyq/libapi/a67]
      - [0x4BCAC, hasm, psyq/libapi/a69]
      - [0x4BCBC, hasm, psyq/libapi/a94]
      - [0x4BCCC, c, psyq/libapi/func_8005B4CC]
      - [0x4BE68, c, psyq/libapi/func_8005B668]
      - [0x4BF6C, hasm, psyq/libapi/a66]
      - [0x4BF7C, c, psyq/libc2/bcopy]
      - [0x4BFB0, c, psyq/libc2/bzero]
      - [0x4BFE0, c, psyq/libc2/memcpy]
      - [0x4C014, c, psyq/libc2/memset]
      - [0x4C044, c, psyq/libc2/rand]
      - [0x4C084, c, psyq/libc2/strcat]
      - [0x4C12C, c, psyq/libc2/strcmp]
      - [0x4C190, c, psyq/libc2/strcpy]
      - [0x4C1D4, c, psyq/libc2/strlen]
      - [0x4C204, c, psyq/libc2/strncat]
      - [0x4C278, c, psyq/libc2/strncpy]
      - [0x4C2F0, c, psyq/libc2/strstr]
      - [0x4C364, c, psyq/libc2/printf]
      - [0x4C3A0, c, psyq/libc2/prnt]
      - [0x4CA28, c, psyq/libc2/ctype]
      - [0x4CA88, c, psyq/libc2/memchr]
      - [0x4CAD8, c, psyq/libc2/putchar]
      - [0x4CB8C, c, psyq/libc2/sprintf]
      - [0x4D3E8, c, psyq/libc2/memmove]
      - [0x4D454, hasm, psyq/libcard/c171]
      - [0x4D464, hasm, psyq/libcard/c172]
      - [0x4D474, hasm, psyq/libcard/card]
      - [0x4D4AC, hasm, psyq/libcard/a78]
      - [0x4D4BC, hasm, psyq/libcard/a80]
      - [0x4D4CC, c, psyq/libcard/init]
      - [0x4D588, hasm, psyq/libapi/a91]
      - [0x4D598, hasm, psyq/libcard/a74]
      - [0x4D5A8, hasm, psyq/libcard/a75]
      - [0x4D5B8, hasm, psyq/libcard/a76]
      - [0x4D5C8, c, psyq/libcard/patch]
      - [0x4D7E8, c, psyq/libpress]
      - [0x4E2E0, c, psyq/libgpu/ext]
      - [0x4E5A8, c, psyq/libgpu/prim]
      - [0x4EE94, c, psyq/libgpu/sys]
      - [0x51F28, hasm, psyq/libapi/c73]
      - [0x51F38, c, psyq/libgpu/tmd]
      - [0x536D4, c, psyq/libgte/geo_00]
      - [0x537A0, c, psyq/libgte/geo_01]
      - [0x53840, c, psyq/libgte/fog_01]
      - [0x538A4, c, psyq/libgte/cor_05]
      - [0x53B24, c, psyq/libgte/msc01]
      - [0x53BB4, c, psyq/libgte/mtx_000]
      - [0x54034, c, psyq/libgte/mtx_09]
      - [0x540C4, c, psyq/libgte/mtx_12]
      - [0x541F4, c, psyq/libgte/reg10]
      - [0x54214, c, psyq/libgte/reg11]
      - [0x54234, c, psyq/libgte/reg12]
      - [0x54254, c, psyq/libgte/reg13]
      - [0x54734, c, psyq/libgte/fgo_04]
      - [0x548D4, c, psyq/libgte/fgo_05]
      - [0x54A74, c, psyq/libgte/fgo_06]
      - [0x54C14, c, psyq/libgte/ratan]
      - [0x54E34, c, psyq/libcd/cdrom]
      - [0x54E64, c, psyq/libcd/event]
      - [0x54F6C, hasm, psyq/libapi/a07]
      - [0x54F7C, c, psyq/libcd/sys]
      - [0x556E8, c, psyq/libcd/bios]
      - [0x56DD0, c, psyq/libc2/puts]
      - [0x56E20, c, psyq/libcd/cdread]
      - [0x57414, c, psyq/libcd/cdread2]
      - [0x574C8, c, psyq/libcd/c_002]
      - [0x57528, c, psyq/libcd/c_003]
      - [0x57670, c, psyq/libcd/c_005]
      - [0x576F8, c, psyq/libcd/c_007]
      - [0x577B0, c, psyq/libcd/c_008]
      - [0x577EC, c, psyq/libcd/c_009]
      - [0x578B0, c, psyq/libcd/c_010]
      - [0x578D0, c, psyq/libcd/c_011]
      - [0x58614, c, psyq/libetc]
      - [0x5BF1C, c, psyq/libsnd]
      - [0x648D4, c, psyq/libspu]
      - [0x67638, data]
      - [0x887A8, sdata]
  - [0x88800]
