name: SCUS_942.36
sha1: 81cbc79f0230aeb4252e058039f47ac95a777f5a
options:
  basename: scus_942.36
  target_path: ./iso/us/SCUS_942.36
  elf_path: ./build/scus_942.36/scus_942.36.elf
  base_path: ../../
  platform: psx
  compiler: PSYQ

  asm_path: ./asm/scus_942.36
  src_path: ./src/scus_942.36
  build_path: ./build
  asset_path: ./assets/scus_942.36
  # create_asm_dependencies: True
  generate_asm_macros_files : False

  ld_script_path: ./linker/scus_942.36/scus_942.36.ld
  ld_dependencies: True

  find_file_boundaries: False
  gp_value: 0x80097FA8
  global_vram_start: 0x80010000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  disassemble_all: true

  section_order: [".rodata", ".text", ".data", ".sdata", ".bss", ".sbss"]
  #auto_link_sections: [".data", ".rodata", ".bss"]
  #migrate_rodata_to_functions: true

  symbol_addrs_path:
    - ./symbols/scus_942.36/symbol_addrs.txt
  reloc_addrs_path:
    - ./symbols/scus_942.36/reloc_addrs.txt

  undefined_funcs_auto_path: ./linker/scus_942.36/undefined_funcs_auto.scus_942.36.txt
  undefined_syms_auto_path: ./linker/scus_942.36/undefined_syms_auto.scus_942.36.txt

  extensions_path: ./tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: True
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x0800
    vram: 0x80010000
    # bss_size: 0x2116f
    align: 4
    subalign: 4
    subsegments:
      - [0x800, .rodata, main/main]
      - [0x8C4, .rodata, main/temp1]
      - [0xB08, .rodata, main/temp2]
      - [0xB84, .rodata, main/temp3]
      - [0xE28, .rodata, main/temp4]
      - [0xF04, .rodata, main/temp5]
      - [0xF48, .rodata, main/temp6]
      - [0xF94, .rodata, main/temp7]
      - [0xFA8, .rodata, main/temp8]
      - [0x3624, .rodata, main/temp9]
      - [0x3FA8, .rodata, main/temp10]
      - [0x4164, .rodata, main/temp11]
      - [0x42A0, .rodata, main/events]
      - [0x4304, .rodata, main/temp13]
      - [0x4350, .rodata, main/temp14]
      - [0x55D4, .rodata, main/temp15]
      - [0x5F3C, .rodata, psyq/libc2/prnt]
      - [0x6150, .rodata, psyq/libc2/sprintf]
      - [0x622C, .rodata, psyq/libpress/libpress]
      - [0x62D8, .rodata, psyq/libgpu/prim]
      - [0x63A8, .rodata, psyq/libgpu/sys]
      - [0x65DC, .rodata, psyq/libgpu/tmd]
      - [0x6714, .rodata, psyq/libcd/event]
      - [0x672C, .rodata, psyq/libcd/sys]
      - [0x6734, .rodata, psyq/libcd/bios]
      - [0x6984, .rodata, psyq/libc2/puts]
      - [0x698C, .rodata, psyq/libcd/cdread]
      - [0x69D0, .rodata, psyq/libcd/c_011]
      - [0x69E8, .rodata, psyq/libetc/vsync]
      - [0x69F8, .rodata, psyq/libetc/intr]
      - [0x6AB0, .rodata, psyq/libsnd/ssopenq]
      - [0x6AD4, .rodata, psyq/libsnd/seqinit]
      - [0x6B10, .rodata, psyq/libsnd/sstick]
      - [0x6B38, .rodata, psyq/libspu/spu]
      - [0x6B70, .rodata, psyq/libspu/s_sca]
      - [0x6BB0, c, main/main]
      - [0xAF74, c, main/temp1]
      - [0x13408, c, main/temp2]
      - [0x19D48, c, main/temp3]
      - [0x1F164, c, main/temp4]
      - [0x22108, c, main/temp5]
      - [0x235B4, c, main/temp6]
      - [0x24164, c, main/temp7]
      - [0x24750, c, main/temp8]
      - [0x24F3C, c, main/temp9]
      - [0x2C924, c, main/temp10]
      - [0x2D1D4, c, main/temp11]
      - [0x2FA68, c, main/events]
      - [0x3197C, c, main/temp13]
      - [0x33B9C, c, main/temp14]
      - [0x4843C, c, main/temp15]
      - [0x4BB8C, hasm, psyq/libapi/c68]
      - [0x4BB9C, hasm, psyq/libapi/c112]
      - [0x4BBAC, hasm, psyq/libapi/a08]
      - [0x4BBBC, hasm, psyq/libapi/a09]
      - [0x4BBCC, hasm, psyq/libapi/a11]
      - [0x4BBDC, hasm, psyq/libapi/a12]
      - [0x4BBEC, hasm, psyq/libapi/a14]
      - [0x4BBFC, hasm, psyq/libapi/a15]
      - [0x4BC0C, hasm, psyq/libapi/a16]
      - [0x4BC1C, hasm, psyq/libapi/a36]
      - [0x4BC2C, hasm, psyq/libapi/a37]
      - [0x4BC3C, hasm, psyq/libapi/a50]
      - [0x4BC4C, hasm, psyq/libapi/a51]
      - [0x4BC5C, hasm, psyq/libapi/a52]
      - [0x4BC6C, hasm, psyq/libapi/a53]
      - [0x4BC7C, hasm, psyq/libapi/a54]
      - [0x4BC8C, hasm, psyq/libapi/a65]
      - [0x4BC9C, hasm, psyq/libapi/a67]
      - [0x4BCAC, hasm, psyq/libapi/a69]
      - [0x4BCBC, hasm, psyq/libapi/a94]
      - [0x4BCCC, c, psyq/libapi/func_8005B4CC]
      - [0x4BE68, c, psyq/libapi/func_8005B668]
      - [0x4BF6C, hasm, psyq/libapi/a66]
      - [0x4BF7C, c, psyq/libc2/bcopy]
      - [0x4BFB0, c, psyq/libc2/bzero]
      - [0x4BFE0, c, psyq/libc2/memcpy]
      - [0x4C014, c, psyq/libc2/memset]
      - [0x4C044, c, psyq/libc2/rand]
      - [0x4C084, c, psyq/libc2/strcat]
      - [0x4C12C, c, psyq/libc2/strcmp]
      - [0x4C190, c, psyq/libc2/strcpy]
      - [0x4C1D4, c, psyq/libc2/strlen]
      - [0x4C204, c, psyq/libc2/strncat]
      - [0x4C278, c, psyq/libc2/strncpy]
      - [0x4C2F0, c, psyq/libc2/strstr]
      - [0x4C364, c, psyq/libc2/printf]
      - [0x4C3A0, c, psyq/libc2/prnt]
      - [0x4CA28, c, psyq/libc2/ctype]
      - [0x4CA88, c, psyq/libc2/memchr]
      - [0x4CAD8, c, psyq/libc2/putchar]
      - [0x4CB8C, c, psyq/libc2/sprintf]
      - [0x4D3E8, c, psyq/libc2/memmove]
      - [0x4D454, hasm, psyq/libcard/c171]
      - [0x4D464, hasm, psyq/libcard/c172]
      - [0x4D474, hasm, psyq/libcard/card]
      - [0x4D4AC, hasm, psyq/libcard/a78]
      - [0x4D4BC, hasm, psyq/libcard/a80]
      - [0x4D4CC, c, psyq/libcard/init]
      - [0x4D588, hasm, psyq/libapi/a91]
      - [0x4D598, hasm, psyq/libcard/a74]
      - [0x4D5A8, hasm, psyq/libcard/a75]
      - [0x4D5B8, hasm, psyq/libcard/a76]
      - [0x4D5C8, c, psyq/libcard/patch]
      - [0x4D7E8, c, psyq/libpress/libpress]
      - [0x4DF4C, c, psyq/libpress/vlc]
      - [0x4E2E0, c, psyq/libgpu/ext]
      - [0x4E5A8, c, psyq/libgpu/prim]
      - [0x4EE94, c, psyq/libgpu/sys]
      - [0x51F28, hasm, psyq/libapi/c73]
      - [0x51F38, c, psyq/libgpu/tmd]
      - [0x536D4, c, psyq/libgte/geo_00]
      - [0x537A0, c, psyq/libgte/geo_01]
      - [0x53840, c, psyq/libgte/fog_01]
      - [0x538A4, c, psyq/libgte/cor_05]
      - [0x53B24, c, psyq/libgte/msc01]
      - [0x53BB4, c, psyq/libgte/mtx_000]
      - [0x54034, c, psyq/libgte/mtx_09]
      - [0x540C4, c, psyq/libgte/mtx_12]
      - [0x541F4, c, psyq/libgte/reg10]
      - [0x54214, c, psyq/libgte/reg11]
      - [0x54234, c, psyq/libgte/reg12]
      - [0x54254, c, psyq/libgte/reg13]
      - [0x54734, c, psyq/libgte/fgo_04]
      - [0x548D4, c, psyq/libgte/fgo_05]
      - [0x54A74, c, psyq/libgte/fgo_06]
      - [0x54C14, c, psyq/libgte/ratan]
      - [0x54E34, c, psyq/libcd/cdrom]
      - [0x54E64, c, psyq/libcd/event]
      - [0x54F6C, hasm, psyq/libapi/a07]
      - [0x54F7C, c, psyq/libcd/sys]
      - [0x556E8, c, psyq/libcd/bios]
      - [0x56DD0, c, psyq/libc2/puts]
      - [0x56E20, c, psyq/libcd/cdread]
      - [0x57414, c, psyq/libcd/cdread2]
      - [0x574C8, c, psyq/libcd/c_002]
      - [0x57528, c, psyq/libcd/c_003]
      - [0x57670, c, psyq/libcd/c_005]
      - [0x576F8, c, psyq/libcd/c_007]
      - [0x577B0, c, psyq/libcd/c_008]
      - [0x577EC, c, psyq/libcd/c_009]
      - [0x578B0, c, psyq/libcd/c_010]
      - [0x578D0, c, psyq/libcd/c_011]
      - [0x58430, c, psyq/libetc/vsync]
      - [0x58614, c, psyq/libapi/l10]
      - [0x58624, c, psyq/libetc/intr]
      - [0x58D54, c, psyq/libapi/a23]
      - [0x58D64, c, psyq/libapi/a24]
      - [0x58D74, c, psyq/libapi/a25]
      - [0x58D84, c, psyq/libc2/setjmp]
      - [0x58E04, c, psyq/libetc/intr_vb]
      - [0x58F2C, c, psyq/libetc/intr_dma]
      - [0x591D4, c, psyq/libetc/vmode]
      - [0x5BF1C, c, psyq/libsnd/ssclose]
      - [0x5C1A4, c, psyq/libsnd/ssinit]
      - [0x5C2BC, c, psyq/libsnd/ssloop]
      - [0x5C34C, c, psyq/libsnd/ssopenq]
      - [0x5C65C, c, psyq/libsnd/cc_0]
      - [0x5C6DC, c, psyq/libsnd/cc_6]
      - [0x5CB0C, c, psyq/libsnd/cc_7]
      - [0x5CBE4, c, psyq/libsnd/cc_10]
      - [0x5CCB4, c, psyq/libsnd/cc_64]
      - [0x5CD64, c, psyq/libsnd/cc_91]
      - [0x5CDF4, c, psyq/libsnd/cc_98]
      - [0x5CF2C, c, psyq/libsnd/cc_99]
      - [0x5D068, c, psyq/libsnd/cc_100]
      - [0x5D0E0, c, psyq/libsnd/cc_101]
      - [0x5D158, c, psyq/libsnd/cc_121]
      - [0x5D21C, c, psyq/libsnd/de_0]
      - [0x5D2AC, c, psyq/libsnd/de_1]
      - [0x5D368, c, psyq/libsnd/de_2]
      - [0x5D3F8, c, psyq/libsnd/de_3]
      - [0x5D488, c, psyq/libsnd/de_4]
      - [0x5D53C, c, psyq/libsnd/ccadsr]
      - [0x5D624, c, psyq/libsnd/de_5]
      - [0x5D6DC, c, psyq/libsnd/de_6]
      - [0x5D78C, c, psyq/libsnd/de_7]
      - [0x5D83C, c, psyq/libsnd/de_8]
      - [0x5D8F0, c, psyq/libsnd/de_9]
      - [0x5D9A8, c, psyq/libsnd/de_10]
      - [0x5DA5C, c, psyq/libsnd/de_11]
      - [0x5DB04, c, psyq/libsnd/de_12]
      - [0x5DBE0, c, psyq/libsnd/de_13]
      - [0x5DC80, c, psyq/libsnd/de_14]
      - [0x5DD20, c, psyq/libsnd/de_15]
      - [0x5DD44, c, psyq/libsnd/de_16]
      - [0x5DDD8, c, psyq/libsnd/midibend]
      - [0x5DE90, c, psyq/libsnd/midicc]
      - [0x5E0D0, c, psyq/libsnd/midimeta]
      - [0x5E2A8, c, psyq/libsnd/midinote]
      - [0x5E390, c, psyq/libsnd/midiprog]
      - [0x5E408, c, psyq/libsnd/miditime]
      - [0x5E4C0, c, psyq/libsnd/seqinit]
      - [0x5E7D8, c, psyq/libsnd/ssplay]
      - [0x5E868, c, psyq/libsnd/playmode]
      - [0x5E968, c, psyq/libsnd/sssmv]
      - [0x5E9B8, c, psyq/libsnd/ssstart]
      - [0x5EC20, c, psyq/libsnd/ut_ron]
      - [0x5EC40, c, psyq/libsnd/ut_roff]
      - [0x5EE60, c, psyq/libsnd/sscall]
      - [0x5F0D4, c, psyq/libsnd/cres]
      - [0x5F3B4, c, psyq/libsnd/decres]
      - [0x5F654, c, psyq/libsnd/pause]
      - [0x5F6F8, c, psyq/libsnd/play]
      - [0x5F724, c, psyq/libsnd/midiread]
      - [0x5FCDC, c, psyq/libsnd/next]
      - [0x5FDE4, c, psyq/libsnd/replay]
      - [0x5FE4C, c, psyq/libsnd/ssstop]
      - [0x60008, c, psyq/libsnd/sstable]
      - [0x601E8, c, psyq/libsnd/sstick]
      - [0x60354, c, psyq/libsnd/ssvol]
      - [0x60428, c, psyq/libsnd/tempo]
      - [0x60608, c, psyq/libsnd/ut_cp]
      - [0x60748, c, psyq/libsnd/ut_gpa]
      - [0x60850, c, psyq/libsnd/ut_gva]
      - [0x60A8C, c, psyq/libsnd/ut_keyv]
      - [0x60E98, c, psyq/libsnd/ut_rdel]
      - [0x60ED8, c, psyq/libsnd/ut_rdep]
      - [0x60F70, c, psyq/libsnd/ut_rev]
      - [0x61024, c, psyq/libsnd/ut_rfb]
      - [0x610A4, c, psyq/libsnd/ut_sva]
      - [0x6126C, c, psyq/libsnd/vm_aloc2]
      - [0x61490, c, psyq/libsnd/vm_don]
      - [0x614A4, c, psyq/libsnd/vm_f]
      - [0x61858, c, psyq/libsnd/vm_init]
      - [0x61B68, c, psyq/libsnd/vm_key]
      - [0x6232C, c, psyq/libsnd/vm_aloc1]
      - [0x62758, c, psyq/libsnd/vm_no1]
      - [0x62C24, c, psyq/libsnd/vm_noff]
      - [0x62C68, c, psyq/libsnd/vm_nowof]
      - [0x62D38, c, psyq/libsnd/vm_nowon]
      - [0x6321C, c, psyq/libsnd/vm_pb]
      - [0x6350C, c, psyq/libsnd/vm_seq]
      - [0x63BF4, c, psyq/libsnd/vm_stav]
      - [0x63CA8, c, psyq/libsnd/vm_vol]
      - [0x6422C, c, psyq/libsnd/vm_vsu]
      - [0x64300, c, psyq/libsnd/vs_mono]
      - [0x64324, c, psyq/libsnd/vs_srv]
      - [0x64354, c, psyq/libsnd/vs_vab]
      - [0x643D8, c, psyq/libsnd/vs_vfb]
      - [0x64448, c, psyq/libsnd/vs_vh]
      - [0x648D4, c, psyq/libspu/s_ini]
      - [0x64A48, c, psyq/libspu/spu]
      - [0x655F4, c, psyq/libspu/s_dcb]
      - [0x65618, c, psyq/libspu/s_q]
      - [0x65694, c, psyq/libapi/a13]
      - [0x656A4, c, psyq/libspu/s_m_init]
      - [0x656F8, c, psyq/libspu/s_m_m]
      - [0x65CC8, c, psyq/libspu/s_m_f]
      - [0x65D44, c, psyq/libspu/s_snv]
      - [0x65D68, c, psyq/libspu/s_sav]
      - [0x65F70, c, psyq/libspu/s_sr]
      - [0x6614C, c, psyq/libspu/s_srmp]
      - [0x66B14, c, psyq/libspu/s_rrwa]
      - [0x66BDC, c, psyq/libspu/s_srv]
      - [0x66C00, c, psyq/libspu/s_crwa]
      - [0x66D9C, c, psyq/libapi/a10]
      - [0x66DAC, c, psyq/libspu/s_sk]
      - [0x66FA8, c, psyq/libspu/s_r]
      - [0x67008, c, psyq/libspu/s_stsa]
      - [0x67060, c, psyq/libspu/s_itc]
      - [0x67108, c, psyq/libspu/s_it]
      - [0x6714C, c, psyq/libspu/s_sca]
      - [0x674E0, c, psyq/libspu/sr_gaks]
      - [0x67638, data]
      - [0x887A8, sdata]
  - [0x88800]
