categories:
  - id: sdk
    name: Psy-Q SDK
    paths:
      - scus_942.36/psyq
  - id: main
    name: Main Executable
    paths:
      - scus_942.36

expected_paths:
  asm: expected/asm
  src: expected/src

ignored_files:
  - scus_942.36/header

output: ./objdiff.json