#include "common.h"
#include "game.h"

INCLUDE_ASM("asm/scus_942.36/nonmatchings/main/unk/temp9b", func_80038570);

INCLUDE_ASM("asm/scus_942.36/nonmatchings/main/unk/temp9b", func_800385EC);

INCLUDE_ASM("asm/scus_942.36/nonmatchings/main/unk/temp9b", func_80038748);

INCLUDE_ASM("asm/scus_942.36/nonmatchings/main/unk/temp9b", func_8003887C);

INCLUDE_ASM("asm/scus_942.36/nonmatchings/main/unk/temp9b", func_80038AC0);

INCLUDE_ASM("asm/scus_942.36/nonmatchings/main/unk/temp9b", func_8003A10C);

INCLUDE_ASM("asm/scus_942.36/nonmatchings/main/unk/temp9b", func_8003A310);

INCLUDE_ASM("asm/scus_942.36/nonmatchings/main/unk/temp9b", func_8003A384);

INCLUDE_ASM("asm/scus_942.36/nonmatchings/main/unk/temp9b", func_8003A4F8);

// INCLUDE_ASM("asm/scus_942.36/nonmatchings/main/unk/temp9b", func_8003A604);
void func_8003A604(int id)
{
    D_8007D6A0 = id;
}

INCLUDE_ASM("asm/scus_942.36/nonmatchings/main/unk/temp9b", func_8003A614);

// INCLUDE_ASM("asm/scus_942.36/nonmatchings/main/unk/temp9b", func_8003A8A8);
u8* func_8003A8A8(s32 n, u8* dst, u8 val)
{
    switch (n) {
    case 255:  *dst++ = val;
    case 254:  *dst++ = val;
    case 253:  *dst++ = val;
    case 252:  *dst++ = val;
    case 251:  *dst++ = val;
    case 250:  *dst++ = val;
    case 249:  *dst++ = val;
    case 248:  *dst++ = val;
    case 247:  *dst++ = val;
    case 246:  *dst++ = val;
    case 245:  *dst++ = val;
    case 244:  *dst++ = val;
    case 243:  *dst++ = val;
    case 242:  *dst++ = val;
    case 241:  *dst++ = val;
    case 240:  *dst++ = val;
    case 239:  *dst++ = val;
    case 238:  *dst++ = val;
    case 237:  *dst++ = val;
    case 236:  *dst++ = val;
    case 235:  *dst++ = val;
    case 234:  *dst++ = val;
    case 233:  *dst++ = val;
    case 232:  *dst++ = val;
    case 231:  *dst++ = val;
    case 230:  *dst++ = val;
    case 229:  *dst++ = val;
    case 228:  *dst++ = val;
    case 227:  *dst++ = val;
    case 226:  *dst++ = val;
    case 225:  *dst++ = val;
    case 224:  *dst++ = val;
    case 223:  *dst++ = val;
    case 222:  *dst++ = val;
    case 221:  *dst++ = val;
    case 220:  *dst++ = val;
    case 219:  *dst++ = val;
    case 218:  *dst++ = val;
    case 217:  *dst++ = val;
    case 216:  *dst++ = val;
    case 215:  *dst++ = val;
    case 214:  *dst++ = val;
    case 213:  *dst++ = val;
    case 212:  *dst++ = val;
    case 211:  *dst++ = val;
    case 210:  *dst++ = val;
    case 209:  *dst++ = val;
    case 208:  *dst++ = val;
    case 207:  *dst++ = val;
    case 206:  *dst++ = val;
    case 205:  *dst++ = val;
    case 204:  *dst++ = val;
    case 203:  *dst++ = val;
    case 202:  *dst++ = val;
    case 201:  *dst++ = val;
    case 200:  *dst++ = val;
    case 199:  *dst++ = val;
    case 198:  *dst++ = val;
    case 197:  *dst++ = val;
    case 196:  *dst++ = val;
    case 195:  *dst++ = val;
    case 194:  *dst++ = val;
    case 193:  *dst++ = val;
    case 192:  *dst++ = val;
    case 191:  *dst++ = val;
    case 190:  *dst++ = val;
    case 189:  *dst++ = val;
    case 188:  *dst++ = val;
    case 187:  *dst++ = val;
    case 186:  *dst++ = val;
    case 185:  *dst++ = val;
    case 184:  *dst++ = val;
    case 183:  *dst++ = val;
    case 182:  *dst++ = val;
    case 181:  *dst++ = val;
    case 180:  *dst++ = val;
    case 179:  *dst++ = val;
    case 178:  *dst++ = val;
    case 177:  *dst++ = val;
    case 176:  *dst++ = val;
    case 175:  *dst++ = val;
    case 174:  *dst++ = val;
    case 173:  *dst++ = val;
    case 172:  *dst++ = val;
    case 171:  *dst++ = val;
    case 170:  *dst++ = val;
    case 169:  *dst++ = val;
    case 168:  *dst++ = val;
    case 167:  *dst++ = val;
    case 166:  *dst++ = val;
    case 165:  *dst++ = val;
    case 164:  *dst++ = val;
    case 163:  *dst++ = val;
    case 162:  *dst++ = val;
    case 161:  *dst++ = val;
    case 160:  *dst++ = val;
    case 159:  *dst++ = val;
    case 158:  *dst++ = val;
    case 157:  *dst++ = val;
    case 156:  *dst++ = val;
    case 155:  *dst++ = val;
    case 154:  *dst++ = val;
    case 153:  *dst++ = val;
    case 152:  *dst++ = val;
    case 151:  *dst++ = val;
    case 150:  *dst++ = val;
    case 149:  *dst++ = val;
    case 148:  *dst++ = val;
    case 147:  *dst++ = val;
    case 146:  *dst++ = val;
    case 145:  *dst++ = val;
    case 144:  *dst++ = val;
    case 143:  *dst++ = val;
    case 142:  *dst++ = val;
    case 141:  *dst++ = val;
    case 140:  *dst++ = val;
    case 139:  *dst++ = val;
    case 138:  *dst++ = val;
    case 137:  *dst++ = val;
    case 136:  *dst++ = val;
    case 135:  *dst++ = val;
    case 134:  *dst++ = val;
    case 133:  *dst++ = val;
    case 132:  *dst++ = val;
    case 131:  *dst++ = val;
    case 130:  *dst++ = val;
    case 129:  *dst++ = val;
    case 128:  *dst++ = val;
    case 127:  *dst++ = val;
    case 126:  *dst++ = val;
    case 125:  *dst++ = val;
    case 124:  *dst++ = val;
    case 123:  *dst++ = val;
    case 122:  *dst++ = val;
    case 121:  *dst++ = val;
    case 120:  *dst++ = val;
    case 119:  *dst++ = val;
    case 118:  *dst++ = val;
    case 117:  *dst++ = val;
    case 116:  *dst++ = val;
    case 115:  *dst++ = val;
    case 114:  *dst++ = val;
    case 113:  *dst++ = val;
    case 112:  *dst++ = val;
    case 111:  *dst++ = val;
    case 110:  *dst++ = val;
    case 109:  *dst++ = val;
    case 108:  *dst++ = val;
    case 107:  *dst++ = val;
    case 106:  *dst++ = val;
    case 105:  *dst++ = val;
    case 104:  *dst++ = val;
    case 103:  *dst++ = val;
    case 102:  *dst++ = val;
    case 101:  *dst++ = val;
    case 100:  *dst++ = val;
    case 99:  *dst++ = val;
    case 98:  *dst++ = val;
    case 97:  *dst++ = val;
    case 96:  *dst++ = val;
    case 95:  *dst++ = val;
    case 94:  *dst++ = val;
    case 93:  *dst++ = val;
    case 92:  *dst++ = val;
    case 91:  *dst++ = val;
    case 90:  *dst++ = val;
    case 89:  *dst++ = val;
    case 88:  *dst++ = val;
    case 87:  *dst++ = val;
    case 86:  *dst++ = val;
    case 85:  *dst++ = val;
    case 84:  *dst++ = val;
    case 83:  *dst++ = val;
    case 82:  *dst++ = val;
    case 81:  *dst++ = val;
    case 80:  *dst++ = val;
    case 79:  *dst++ = val;
    case 78:  *dst++ = val;
    case 77:  *dst++ = val;
    case 76:  *dst++ = val;
    case 75:  *dst++ = val;
    case 74:  *dst++ = val;
    case 73:  *dst++ = val;
    case 72:  *dst++ = val;
    case 71:  *dst++ = val;
    case 70:  *dst++ = val;
    case 69:  *dst++ = val;
    case 68:  *dst++ = val;
    case 67:  *dst++ = val;
    case 66:  *dst++ = val;
    case 65:  *dst++ = val;
    case 64:  *dst++ = val;
    case 63:  *dst++ = val;
    case 62:  *dst++ = val;
    case 61:  *dst++ = val;
    case 60:  *dst++ = val;
    case 59:  *dst++ = val;
    case 58:  *dst++ = val;
    case 57:  *dst++ = val;
    case 56:  *dst++ = val;
    case 55:  *dst++ = val;
    case 54:  *dst++ = val;
    case 53:  *dst++ = val;
    case 52:  *dst++ = val;
    case 51:  *dst++ = val;
    case 50:  *dst++ = val;
    case 49:  *dst++ = val;
    case 48:  *dst++ = val;
    case 47:  *dst++ = val;
    case 46:  *dst++ = val;
    case 45:  *dst++ = val;
    case 44:  *dst++ = val;
    case 43:  *dst++ = val;
    case 42:  *dst++ = val;
    case 41:  *dst++ = val;
    case 40:  *dst++ = val;
    case 39:  *dst++ = val;
    case 38:  *dst++ = val;
    case 37:  *dst++ = val;
    case 36:  *dst++ = val;
    case 35:  *dst++ = val;
    case 34:  *dst++ = val;
    case 33:  *dst++ = val;
    case 32:  *dst++ = val;
    case 31:  *dst++ = val;
    case 30:  *dst++ = val;
    case 29:  *dst++ = val;
    case 28:  *dst++ = val;
    case 27:  *dst++ = val;
    case 26:  *dst++ = val;
    case 25:  *dst++ = val;
    case 24:  *dst++ = val;
    case 23:  *dst++ = val;
    case 22:  *dst++ = val;
    case 21:  *dst++ = val;
    case 20:  *dst++ = val;
    case 19:  *dst++ = val;
    case 18:  *dst++ = val;
    case 17:  *dst++ = val;
    case 16:  *dst++ = val;
    case 15:  *dst++ = val;
    case 14:  *dst++ = val;
    case 13:  *dst++ = val;
    case 12:  *dst++ = val;
    case 11:  *dst++ = val;
    case 10:  *dst++ = val;
    case 9:  *dst++ = val;
    case 8:  *dst++ = val;
    case 7:  *dst++ = val;
    case 6:  *dst++ = val;
    case 5:  *dst++ = val;
    case 4:  *dst++ = val;
    case 3:  *dst++ = val;
    case 2:  *dst++ = val;
    case 1:  *dst++ = val;
    }
    return dst;
}
