name: SCUS_942.36
sha1: 81cbc79f0230aeb4252e058039f47ac95a777f5a
options:
  basename: scus_942.36
  target_path: ./iso/us/SCUS_942.36
  elf_path: ./build/us/scus_942.36.elf
  base_path: ../../
  platform: psx
  compiler: PSYQ

  asm_path: ./asm/us
  src_path: ./src/us
  build_path: ./build/us
  asset_path: ./assets/us
  # create_asm_dependencies: True

  ld_script_path: ./linker/us/scus_942.36.ld
  ld_dependencies: True

  find_file_boundaries: True
  gp_value: 0x80097FA8

  o_as_suffix: True
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  disassemble_all: true

  section_order: [".rodata", ".text", ".data", ".bss"]
  auto_link_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path:
    - ./symbols/us/symbol_addrs.txt
  reloc_addrs_path:
    - ./symbols/us/reloc_addrs.txt

  undefined_funcs_auto_path: ./symbols/us/undefined_funcs_auto.txt
  undefined_syms_auto_path: ./symbols/us/undefined_syms_auto.txt

  extensions_path: ./tools/splat_ext

  subalign: 2

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x0800
    vram: 0x80010000
    # bss_size: Please fill out this value when you figure out the bss size
    subsegments:
      - [0x0800, .rodata]
      - [0x6BB0, c, game, main]
      - [0x4BB8C, c, psyq37/libapi, c68]
      - [0x4BB9C, c, psyq37/libapi, c112]
      - [0x4BBAC, c, psyq37/libapi, a08]
      - [0x4BBBC, c, psyq37/libapi, a09]
      - [0x4BBCC, c, psyq37/libapi, a11]
      - [0x4BBDC, c, psyq37/libapi, a12]
      - [0x4BBEC, c, psyq37/libapi, a14]
      - [0x4BBFC, c, psyq37/libapi, a15]
      - [0x4BC0C, c, psyq37/libapi, a16]
      - [0x4BC1C, c, psyq37/libapi, a36]
      - [0x4BC2C, c, psyq37/libapi, a37]
      - [0x4BC3C, c, psyq37/libapi, a50]
      - [0x4BC4C, c, psyq37/libapi, a51]
      - [0x4BC5C, c, psyq37/libapi, a52]
      - [0x4BC6C, c, psyq37/libapi, a53]
      - [0x4BC7C, c, psyq37/libapi, a54]
      - [0x4BC8C, c, psyq37/libapi, a65]
      - [0x4BC9C, c, psyq37/libapi, a67]
      - [0x4BCAC, c, psyq37/libapi, a69]
      - [0x4BCBC, c, psyq37/libapi, a94]
      - [0x4BF6C, c, psyq37/libapi, a66]
      - [0x4BF7C, c, psyq37/libapi, realloc2]
      - [0x4BFB0, c, psyq37/libapi, calloc2]
      - [0x4BFE0, c, psyq37/libc2, memcpy]
      - [0x4C014, c, psyq37/libc2, memset]
      - [0x4C044, c, psyq37/libc2, rand]
      - [0x4C084, c, psyq37/libc2, strcat]
      - [0x4C12C, c, psyq37/libc2, strcmp]
      - [0x4C190, c, psyq37/libc2, strcpy]
      - [0x4C1D4, c, psyq37/libc2, strlen]
      - [0x4C204, c, psyq37/libc2, strncat]
      - [0x4C278, c, psyq37/libc2, strncpy]
      - [0x4C2F0, c, psyq37/libc2, strstr]
      - [0x4C364, c, psyq37/libc2, printf]
      - [0x4C3A0, c, psyq37/libc2, prnt]
      - [0x4CA28, c, psyq37/libc2, ctype]
      - [0x4CA88, c, psyq37/libc2, memchr]
      - [0x4CAD8, c, psyq37/libc2, putchar]
      - [0x4CB8C, c, psyq37/libc2, sprintf]
      - [0x4D3E8, c, psyq37/libc2, memmove]
      - [0x4D454, c, psyq37/libcard, c171]
      - [0x4D464, c, psyq37/libcard, c172]
      - [0x4D474, c, psyq37/libcard, card]
      - [0x4D4AC, c, psyq37/libcard, a78]
      - [0x4D4BC, c, psyq37/libcard, a80]
      - [0x4D4CC, c, psyq37/libcard, init]
      - [0x4D598, c, psyq37/libcard, a74]
      - [0x4D5A8, c, psyq37/libcard, a75]
      - [0x4D5B8, c, psyq37/libcard, a76]
      - [0x4D5C8, c, psyq37/libcard, patch]
      - [0x4D7E8, c, psyq37/libpress, libpress]
      - [0x4DF48, c, psyq37/libpress, vlc]
      - [0x4E2E0, c, psyq37/libgpu, ext]
      - [0x4E5A8, c, psyq37/libgpu, prim]
      - [0x4EE94, c, psyq37/libgpu, sys]
      - [0x51F38, c, psyq37/libgpu, tmd]
      - [0x536D4, c, psyq37/libgte, geo_00]
      - [0x537A0, c, psyq37/libgte, geo_01]
      - [0x53840, c, psyq37/libgte, fog_01]
      - [0x538A4, c, psyq37/libgte, cor_05]
      - [0x53B24, c, psyq37/libgte, msc01]
      - [0x53BB4, c, psyq37/libgte, mtx_000]
      - [0x54034, c, psyq37/libgte, mtx_09]
      - [0x540C4, c, psyq37/libgte, mtx_12]
      - [0x541F4, c, psyq37/libgte, reg10]
      - [0x54214, c, psyq37/libgte, reg11]
      - [0x54234, c, psyq37/libgte, reg12]
      - [0x54254, c, psyq37/libgte, reg13]
      - [0x54734, c, psyq37/libgte, fgo_04]
      - [0x548D4, c, psyq37/libgte, fgo_05]
      - [0x54A74, c, psyq37/libgte, fgo_06]
      - [0x54C14, c, psyq37/libgte, ratan]
      - [0x54E34, c, psyq37/libcd, cdrom]
      - [0x54E64, c, psyq37/libcd, event]
      - [0x54F7C, c, psyq37/libcd, sys]
      - [0x556E8, c, psyq37/libcd, bios]
      - [0x56E20, c, psyq37/libcd, cdread]
      - [0x57414, c, psyq37/libcd, cdread2]
      - [0x574C8, c, psyq37/libcd, c_002]
      - [0x57528, c, psyq37/libcd, c_003]
      - [0x57670, c, psyq37/libcd, c_005]
      - [0x576F8, c, psyq37/libcd, c_007]
      - [0x577B0, c, psyq37/libcd, c_008]
      - [0x577EC, c, psyq37/libcd, c_009]
      - [0x578B0, c, psyq37/libcd, c_010]
      - [0x578D0, c, psyq37/libcd, c_011]
      - [0x58898, c, psyq37/libetc, intr]
      - [0x58D08, c, psyq37/libetc, intr_vb]
      - [0x58E04, c, psyq37/libetc, intr_vb]
      - [0x58F2C, c, psyq37/libetc, intr_dma]
      - [0x591D4, c, psyq37/libetc, vmode]
      - [0x5BF1C, c, psyq37/libsnd, ssclose]
      - [0x5C1A4, c, psyq37/libsnd, ssinit]
      - [0x5C2BC, c, psyq37/libsnd, ssloop]
      - [0x5C34C, c, psyq37/libsnd, ssopenq]
      - [0x5C65C, c, psyq37/libsnd, cc_0]
      - [0x5C6DC, c, psyq37/libsnd, cc_6]
      - [0x5CB0C, c, psyq37/libsnd, cc_7]
      - [0x5CBE4, c, psyq37/libsnd, cc_10]
      - [0x5CCB4, c, psyq37/libsnd, cc_64]
      - [0x5CD64, c, psyq37/libsnd, cc_91]
      - [0x5CDF4, c, psyq37/libsnd, cc_98]
      - [0x5CF2C, c, psyq37/libsnd, cc_99]
      - [0x5D068, c, psyq37/libsnd, cc_100]
      - [0x5D0E0, c, psyq37/libsnd, cc_101]
      - [0x5D158, c, psyq37/libsnd, cc_121]
      - [0x5D21C, c, psyq37/libsnd, de_0]
      - [0x5D2AC, c, psyq37/libsnd, de_1]
      - [0x5D368, c, psyq37/libsnd, de_2]
      - [0x5D3F8, c, psyq37/libsnd, de_3]
      - [0x5D488, c, psyq37/libsnd, de_4]
      - [0x5D53C, c, psyq37/libsnd, ccadsr]
      - [0x5D624, c, psyq37/libsnd, de_5]
      - [0x5D6DC, c, psyq37/libsnd, de_6]
      - [0x5D78C, c, psyq37/libsnd, de_7]
      - [0x5D83C, c, psyq37/libsnd, de_8]
      - [0x5D8F0, c, psyq37/libsnd, de_9]
      - [0x5D9A8, c, psyq37/libsnd, de_10]
      - [0x5DA5C, c, psyq37/libsnd, de_11]
      - [0x5DB04, c, psyq37/libsnd, de_12]
      - [0x5DBE0, c, psyq37/libsnd, de_13]
      - [0x5DC80, c, psyq37/libsnd, de_14]
      - [0x5DD20, c, psyq37/libsnd, de_15]
      - [0x5DD20, c, psyq37/libsnd, de_17]
      - [0x5DD20, c, psyq37/libsnd, de_18]
      - [0x5DD20, c, psyq37/libsnd, de_19]
      - [0x5DD44, c, psyq37/libsnd, de_16]
      - [0x5DDD8, c, psyq37/libsnd, midibend]
      - [0x5DE90, c, psyq37/libsnd, midicc]
      - [0x5E0D0, c, psyq37/libsnd, midimeta]
      - [0x5E2A8, c, psyq37/libsnd, midinote]
      - [0x5E390, c, psyq37/libsnd, midiprog]
      - [0x5E408, c, psyq37/libsnd, miditime]
      - [0x5E4C0, c, psyq37/libsnd, seqinit]
      - [0x5E7D8, c, psyq37/libsnd, ssplay]
      - [0x5E868, c, psyq37/libsnd, playmode]
      - [0x5E968, c, psyq37/libsnd, sssmv]
      - [0x5E9B8, c, psyq37/libsnd, ssstart]
      - [0x5EC20, c, psyq37/libsnd, ut_ron]
      - [0x5EC20, c, psyq37/libspu, s_ih]
      - [0x5EC40, c, psyq37/libsnd, ut_roff]
      - [0x5EC40, c, psyq37/libspu, s_i]
      - [0x5EE60, c, psyq37/libsnd, sscall]
      - [0x5F0D4, c, psyq37/libsnd, cres]
      - [0x5F3B4, c, psyq37/libsnd, decres]
      - [0x5F654, c, psyq37/libsnd, pause]
      - [0x5F6F8, c, psyq37/libsnd, play]
      - [0x5F724, c, psyq37/libsnd, midiread]
      - [0x5FCDC, c, psyq37/libsnd, next]
      - [0x5FDE4, c, psyq37/libsnd, replay]
      - [0x5FE4C, c, psyq37/libsnd, ssstop]
      - [0x60008, c, psyq37/libsnd, sstable]
      - [0x601E8, c, psyq37/libsnd, sstick]
      - [0x60354, c, psyq37/libsnd, ssvol]
      - [0x60428, c, psyq37/libsnd, tempo]
      - [0x60608, c, psyq37/libsnd, ut_cp]
      - [0x60748, c, psyq37/libsnd, ut_gpa]
      - [0x60850, c, psyq37/libsnd, ut_gva]
      - [0x60A8C, c, psyq37/libsnd, ut_keyv]
      - [0x60E98, c, psyq37/libsnd, ut_rdel]
      - [0x60ED8, c, psyq37/libsnd, ut_rdep]
      - [0x60F70, c, psyq37/libsnd, ut_rev]
      - [0x61024, c, psyq37/libsnd, ut_rfb]
      - [0x610A4, c, psyq37/libsnd, ut_sva]
      - [0x6126C, c, psyq37/libsnd, vm_aloc2]
      - [0x61490, c, psyq37/libsnd, vm_don]
      - [0x614A4, c, psyq37/libsnd, vm_f]
      - [0x61858, c, psyq37/libsnd, vm_init]
      - [0x61B68, c, psyq37/libsnd, vm_key]
      - [0x6232C, c, psyq37/libsnd, vm_aloc1]
      - [0x62758, c, psyq37/libsnd, vm_no1]
      - [0x62C24, c, psyq37/libsnd, vm_noff]
      - [0x62C68, c, psyq37/libsnd, vm_nowof]
      - [0x62D38, c, psyq37/libsnd, vm_nowon]
      - [0x6321C, c, psyq37/libsnd, vm_pb]
      - [0x6350C, c, psyq37/libsnd, vm_seq]
      - [0x63BF4, c, psyq37/libsnd, vm_stav]
      - [0x63CA8, c, psyq37/libsnd, vm_vol]
      - [0x6422C, c, psyq37/libsnd, vm_vsu]
      - [0x64300, c, psyq37/libsnd, vs_mono]
      - [0x64324, c, psyq37/libsnd, vs_srv]
      - [0x64354, c, psyq37/libsnd, vs_vab]
      - [0x643D8, c, psyq37/libsnd, vs_vfb]
      - [0x64448, c, psyq37/libsnd, vs_vh]
      - [0x648D4, c, psyq37/libspu, s_ini]
      - [0x64A48, c, psyq37/libspu, spu]
      - [0x655F4, c, psyq37/libspu, s_dcb]
      - [0x65618, c, psyq37/libspu, s_q]
      - [0x656A4, c, psyq37/libspu, s_m_init]
      - [0x656F8, c, psyq37/libspu, s_m_m]
      - [0x65CC8, c, psyq37/libspu, s_m_f]
      - [0x65D44, c, psyq37/libspu, s_snv]
      - [0x65D68, c, psyq37/libspu, s_sav]
      - [0x65F70, c, psyq37/libspu, s_sr]
      - [0x6614C, c, psyq37/libspu, s_srmp]
      - [0x66B14, c, psyq37/libspu, s_rrwa]
      - [0x66BDC, c, psyq37/libspu, s_srv]
      - [0x66C00, c, psyq37/libspu, s_crwa]
      - [0x66DAC, c, psyq37/libspu, s_sk]
      - [0x66FA8, c, psyq37/libspu, s_r]
      - [0x66FA8, c, psyq37/libspu, s_w]
      - [0x67008, c, psyq37/libspu, s_stsa]
      - [0x67060, c, psyq37/libspu, s_itc]
      - [0x67108, c, psyq37/libspu, s_it]
      - [0x6714C, c, psyq37/libspu, s_sca]
      - [0x674E0, c, psyq37/libspu, sr_gaks]
  - [0x88800]
